### ISSUE TITLE
css exclamation mark

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/violencia-indigena#31]
Como visto em http://violenciaindigena.infoamazonia.org/#!/p/942/ (em vermelho)

**Comment by miguelpeixe** [comment]
não entendi isso, porque a exclamação está alinhada a esquerda?

**Comment by bwstefano** [comment]
A ideia deste CSS não se refere só ao ponto de exclamação. É criar uma nota de alerta que seja mais discreta. Então, se refere a toda a área de "! Este aviso tem link. Precisa ser mais discreto e com um ícone de aviso à esquerda”. O ponto de exclamação é um indicador de local onde poderia haver um ícone tipo algum desses: https://thenounproject.com/search/?q=exclamation+mark https://thenounproject.com/search/?q=exclamation+mark

**Comment by miguelpeixe** [comment]
Solucionado com o shortcode `warning`

Exemplo:

```
[warning color="#f00"]Isto é um aviso[/warning]
```

O parâmetro `color` é opcional
