### ISSUE TITLE
Lista para nomes do expediente

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/violencia-indigena#36]
O expediente será organizado por entidade e terá os nomes de cada envolvido, seguidos por suas respectivas funções. Daí, uma possibilidade seria ter os nomes das entidades à esquerda alinhados à direita e, logo ao lado, os nomes de cada pessoa, um por linha, alinhados à esquerda. Um exemplo é http://somai.org/#!/sobre/dados/, mas com alinhamento vertical dos envolvidos em cada entidade acima, e não ao meio, como no exemplo do Somai.

**Comment by miguelpeixe** [comment]
esse tipo de informação/diagramação não estava prevista anteriormente, difícil encaixar nessa etapa do projeto

**Comment by bwstefano** [comment]
Como a gente pode fazer, então? Coloquei nesta etapa imaginando que seria fácil de se resolver.
Se você preferir, pode puxar para o média-baixa ou criar uma outra estrutura para apresentar de maneira adequada o expediente, que já está aqui: http://violenciaindigena.infoamazonia.org/#!/p/1011/ http://violenciaindigena.infoamazonia.org/#!/p/1011/

**Comment by miguelpeixe** [comment]
sugiro usar as formatações disponíveis, apenas melhorar a visualização. um exemplo é [essa página](http://somai.org/#!/parceiros/): logo centralizado e descrição
