### ISSUE TITLE
Exportação CSV: coordenadas faltando

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/violencia-indigena#38]
Em alguns casos, a coluna _coordinates_ mostra "false" como resultado

![image 6](https://cloud.githubusercontent.com/assets/11841075/12664816/f8cf9f4e-c619-11e5-9667-e2a80e2bdd47.png)

**Comment by miguelpeixe** [comment]
pelo que pude observar, os que não tem coordenadas são casos que não tem cod_ibge nem cod_funai, ou seja, não há como verificar localização

**Comment by miguelpeixe** [comment]
pelo que pude observar, os que não tem coordenadas são casos que não tem cod_ibge nem cod_funai, ou seja, não há como verificar localização

**Comment by miguelpeixe** [comment]
e existem novos casos onde a localização não foi dada.
a geolocalização automática foi feita a casos retroativos, não é um script que executa toda vez que um post é criado. novos casos deverão ser geolocalizados. de preferência em procura de uma precisão melhor

**Comment by miguelpeixe** [comment]
existe também uma pequena chance de alguns casos não serem geolocalizados por problemas ao encontrar o local, talvez porque não exista tal municipio/ti na base de dados.

vale ressaltar que se as coordenadas não estão no CSV, elas não estão na base de dados
