### ISSUE TITLE
Facilitar escolha de casos relacionados a um dossiê (backend)

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/violencia-indigena#42]
Na interface de administração, é necessária a criação de alguma forma de seleção rápida dos casos relacionados aos dossiês – talvez seguindo a mesma lógica dos filtros? Da maneira como está, mesmo que fosse possível, ficaria complicado demais, por exemplo, selecionar um por um todos os 400 casos relacionados ao Mato Grosso do Sul

**Comment by miguelpeixe** [comment]
Agora pode ser feita a escolha de casos através de um filtro por metadados, o filtro é realizado de forma dinâmica na interface de visualização do dossiê.

Exemplo:

```
uf=Bahia; povo=Pataxó;
```

![caso_rel](https://cloud.githubusercontent.com/assets/820752/13208030/a862196e-d8f3-11e5-95cc-ec6a6a9c1cf4.png)
