### ISSUE TITLE
Organizar lista de casos por ordem alfabética

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/violencia-indigena#70]

**Comment by bwstefano** [comment]
Ok, mas isso fez com que as quatro primeiras páginas da lista geral de casos ficassem com indígenas sem nome nos registros. É possível manter a ordem alfabética, mas deixar os casos em que os nomes dos indígenas estão ausentes fiquem para o final da lista?

**Comment by miguelpeixe** [comment]
isso não é possível :cry:

**Comment by miguelpeixe** [comment]
ok
