### ISSUE TITLE
Página “Dados abertos”: criar espaçamento específico para botões de download de dados e acesso à fonte

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/violencia-indigena#79]

**Comment by miguelpeixe** [comment]
de que forma? não entendi

**Comment by bwstefano** [comment]
Os botões precisam ficar sempre em um mesmo lugar: sob a imagem, ao invés de ser relativo ao comprimento do texto. As diferenças de posicionamento aparecem nesta imagem.

![botoes](https://cloud.githubusercontent.com/assets/11841075/15640373/b280d720-260d-11e6-9f54-07dfaa3d689c.png)

**Comment by miguelpeixe** [comment]
encapsular os botões a uma div de classe "clearfix"
exemplo:
`<div class="clearfix">[botoes aqui]</div>`
