### ISSUE TITLE
Página “Sobre os casos”: Criar estilo CSS para inclusão de créditos de autoria idêntica aos dos dossiês

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/violencia-indigena#81]

**Comment by miguelpeixe** [comment]
utilizar `<p class="author"></p>`

**Comment by bwstefano** [comment]
Esta alteração ficou boa, mas eu me referia à área de autoria e descrição do autor que fica no final da página, semelhante à existente nos posts dos dossiês

**Comment by miguelpeixe** [comment]
Foi discutido em reunião que não seria implementado dessa forma, porque a parte de autor do rodapé é desacoplada do corpo do content. Foi estabelecido esse formato, explicado acima.
