### ISSUE TITLE
metadados no single case

### ISSUE THREAD

**Issue by miguelpeixe** [ecodigital/violencia-indigena#9]

**Comment by bwstefano** [comment]
Penso que poderiam ser incluídos todos os metadados que se encontram na lista lateral. E desta lista lateral, poderiam sair a aldeia e o relatório de origem. A primeira é uma fração muito pequena, sem correspondência georreferenciada, de um território. A segunda não é tão relevante para ficar na barra lateral e a remoção pode nos poupar algum espaço.
